# Generated by Django 2.2b1 on 2019-02-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('questions', models.CharField(max_length=200)),
            ],
        ),
    ]
